version: "3.9"
services:
  web:
    build: ./app
    ports: ["3000:3000"]
    environment:
      PORT: 3000
      MONGO_URL: mongodb://db:27017/app
    depends_on: [db]
  db:
    image: mongo:6
    volumes: ["dbdata:/data/db"]
volumes:
  dbdata:
